LANGUAGES = {
    "Auto Detect": "auto",

    # Châu Á
    "Tiếng Việt": "vi",
    "Tiếng Trung (Giản thể)": "zh",
    "Tiếng Trung (Phồn thể)": "zh-tw",
    "Tiếng Nhật": "ja",
    "Tiếng Hàn": "ko",
    "Tiếng Thái": "th",
    "Tiếng Indonesia": "id",
    "Tiếng Hindi": "hi",
    "Tiếng Urdu": "ur",
    "Tiếng Bengal (Bengali)": "bn",
    "Tiếng Tamil": "ta",
    "Tiếng Telugu": "te",
    "Tiếng Gujarati": "gu",
    "Tiếng Kannada": "kn", 
    "Tiếng Malayalam": "ml",
    "Tiếng Marathi": "mr",
    "Tiếng Nepali": "ne",
    "Tiếng Sinhala": "si",
    "Tiếng Tagalog": "tl",
    
    # Châu Âu
    "Tiếng Anh": "en",
    "Tiếng Pháp": "fr",
    "Tiếng Đức": "de",
    "Tiếng Tây Ban Nha": "es",
    "Tiếng Bồ Đào Nha": "pt",
    "Tiếng Ý": "it",
    "Tiếng Hà Lan": "nl",
    "Tiếng Nga": "ru",
    "Tiếng Ukraina": "uk",
    "Tiếng Ba Lan": "pl",
    "Tiếng Thụy Điển": "sv",
    "Tiếng Na Uy": "no",
    "Tiếng Đan Mạch": "da",
    "Tiếng Phần Lan": "fi",
    "Tiếng Séc": "cs",
    "Tiếng Slovak": "sk",
    "Tiếng Bulgaria": "bg",
    "Tiếng Romania": "ro",
    "Tiếng Hungary": "hu",
    "Tiếng Croatia": "hr",
    "Tiếng Latvia": "lv",
    "Tiếng Lithuania": "lt",
    "Tiếng Slovenia": "sl",
    "Tiếng Albania": "sq",
    "Tiếng Hy Lạp": "el",
    
    # Trung Đông và Châu Phi
    "Tiếng Ả Rập": "ar",
    "Tiếng Do Thái": "he",
    "Tiếng Thổ Nhĩ Kỳ": "tr",
    "Tiếng Ba Tư (Farsi)": "fa",
    "Tiếng Swahili": "sw",
    "Tiếng Somali": "so",
    "Tiếng Hausa": "ha",
    "Tiếng Yoruba": "yo",
    "Tiếng Igbo": "ig",
    "Tiếng Zulu": "zu",
    "Tiếng Xhosa": "xh",
    "Tiếng Malay": "ms",
    "Tiếng Iceland": "is",
    "Tiếng Welsh": "cy",
    "Tiếng Esperanto": "eo",

}
